name: wisherr
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: wisherr-backend:local
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
      args:
        REACT_APP_API_URL: http://localhost:8000
    image: wisherr-frontend:local
